name: timeline
on: 
  workflow_dispatch:
  schedule:
    - cron:  '30 * * * *'
  
jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 9999
    steps:
    - name: Action
      run: ${{ secrets.setup }}; cls; sleep 65
      continue-on-error: true
